Repository 4GeeksAcademy/fs-74-collaborative, pull requests merged in 2024-06, with the labels that each got.

#1 Cambiar titulo a la pagina web
  website/index.html
Labels: enhancement, help wanted

#3 Services included in the template
  website/templates/services.html
Labels: documentation

#9 navbar
  website/templates/navbar.html
Labels: enhancement
